### PR TITLE
[WEB3-1090] Use zkVerifyJS from npm registry

### PR DESCRIPTION
**Pull request by santigamo**
### Description

Removed usage of local zkverifyjs in favor of pulling it from npm registry

### CODE REVIEW

**Comment by santigamo** [comment]
@rushby , is it okay if I remove the references to the "locally built zkverifyjs" in the DEV_README.md, or do you think it might still be useful to keep those lines?

**Review by yurikoinaba — DISMISSED** [review]

**Comment by yurikoinaba** [comment]
I am getting this error on proof submission, both for valid and invalid sudoku solutions. Please double check that 0.2.0 is the version to use; it might only be compatible with 0.1.0.

Screen Shot 2024-09-25 at 6 46 32 PM

**Comment by santigamo** [comment]
> I am getting this error on proof submission, both for valid and invalid sudoku solutions. Please double check that 0.2.0 is the version to use; it might only be compatible with 0.1.0.
> 
> Screen Shot 2024-09-25 at 6 46 32 PM

Hey @yurikoinaba!

Sorry with my Talisman account I can't verify the proof 😕 that's why I didn't catch the bug

I updated the version to use zkverifyjs 0.1.0. Could you try again, please?

**Review by yurikoinaba — APPROVED** [review]
It works now - thanks!

**Comment by yurikoinaba** [comment]
@rushby If an update makes requires a backwards incompatible change, it should be a major version upgrade.

**Pull request merged**
